### ISSUE TITLE
Upgrade to ruby:2.7

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/canvas#113]
Ruby version [2.6 goes EOL on March 31 2022. ](https://endoflife.date/ruby)We should upgrade this to a supported version of ruby to build and run on Openshift. ruby:2.7 should be sufficient for now.

https://github.com/tl-its-umich-edu/canvas/blob/139ccb9503b9dfcebedf09493fd4bfa0518c03f6/SIS_import/Dockerfile#L2

**Comment by zqian** [comment]
This is included in [issue_112](https://github.com/tl-its-umich-edu/canvas/issues/112)
