### ISSUE TITLE
reorg of properties file setup for sis_upload.rb

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/canvas#24]
Currently, we invoke sis_upload.rb via the following format:

ruby sis_upload.rb PATH_TO_TOKEN_FILE   SERVER_URL   WORKING_DIRECTORY_PATH

In the future, we want to put token, and service url settings into securities.properties, create another properties.txt file for other properties settings (working directory path and the sleep intervals between Canvas API calls), so the command line format will be:

ruby sis_upload.rb PATH_TO_SECURITY_FILE   PATH_TO_PROPERTIES_FILE

**Comment by dlhaines** [comment]
Why would the working directory need to be in security.properties?

**Comment by zqian** [comment]
updated based on Dave's feedback.

Security file now have two params: token and server url;
and properties file have two params: working directory path and sleep seconds.

**Comment by zqian** [comment]
code updated based on feedbacks. Close the issue now.
